name: Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject token
        run: echo "export const GENIUS_TOKEN = '${{ secrets.GENIUS_ACCESS_TOKEN }}';" > src/js/config.js
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GENIUS_ACCESS_TOKEN }}
          publish_dir: ./src